### ISSUE TITLE
can't work on 5.7.20 version

### ISSUE THREAD

**Issue by ryanlycch** [JingMatrix/keygen_master_pdf_editor#1]
thanks for your job. It can't activate on master pdf editor 5.7.20 linux version.

**Comment by JingMatrix** [comment]
When use it, you need to be offline.

**Comment by tttonyalpha** [comment]
Same bro, ubuntu 20.04 master-pdf-editor version: 5.7.20. I've try to be offline when press activate, but it doesn't help. ID: 00000031-0031-0032-3637-313434383831-572, can you send me codes ?

**Comment by tttonyalpha** [comment]
Just now i've try to use keygen by radixx11r in wine and it's doesn't work again ...

**Comment by tttonyalpha** [comment]
I think, i solved problem ! As it mentions here: [https://aur.archlinux.org/packages/masterpdfeditor-libs-included ](url) "I discovered that version 5.6.80 is the very last which can be registered with keygen". You can download 5.6.80 from this link: [https://code-industry.ru/public/](url), I've install this version: master-pdf-editor-5.6.80-qt5.x86_64.deb. Then i ran keygen form this link in wine: [https://www.upload.ee/files/8530776/MPDFE5K_Src.zip.html](url) and get my keys, which worked!

**Comment by JingMatrix** [comment]
Thank you for this important information, I will add this to README.

**Comment by aquac** [comment]
Thanks for the hint regarding the version, but I also had to block the program from accessing the web. I blocked "reg.code-industry.net" via /etc/hosts

**Comment by NewRedsquare** [comment]
> Thanks for the hint regarding the version, but I also had to block the program from accessing the web. I blocked "reg.code-industry.net" via /etc/hosts

I agree, please add it to README.
