### ISSUE TITLE
Cannot download the RPM file for 5.6.80 on Wayback Machine

### ISSUE THREAD

**Issue by sith-on-mars** [JingMatrix/keygen_master_pdf_editor#2]
I believe [this link](https://web.archive.org/web/20210116165107/https://code-industry.net/free-pdf-editor/) is the snapshot for 5.6.80. But the link for the RPM version (master-pdf-editor-5.6.80-qt5_included.x86_64.rpm) doesn't work.

**Comment by JingMatrix** [comment]
This is not really an issue relating to my code, but anyway you can find an
interesting version for you here:
https://web.archive.org/web/*/https://code-industry.net/public/*
